# Generated by Django 5.2.8 on 2026-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelpackage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="packages/"),
        ),
    ]
