# Generated by Django 5.2.7 on 2025-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='itinerary',
            field=models.JSONField(default=list),
        ),
    ]
