# Generated by Django 5.2.7 on 2025-10-31 05:11

from django.db import migrations

def update_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    domain = '127.0.0.1:8000'
    
    # Check if the default site exists
    if Site.objects.filter(pk=1).exists():
        site = Site.objects.get(pk=1)
        site.domain = domain
        site.name = domain
        site.save()
    else:
        # If it doesn't exist for some reason, create it
        Site.objects.create(pk=1, domain=domain, name=domain)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_travelpackage_itinerary'),
        # Add a dependency on the sites app's initial migration
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]