# Generated by Django 5.2.8 on 2026-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_travelpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
