# Generated by Django 5.2.8 on 2026-03-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_customitinerary_packageday_packagedayoption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="custom_itinerary",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="main.customitinerary",
            ),
        ),
    ]
