# Generated by Django 5.2.8 on 2025-12-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_update_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
