# Generated by Django 5.2.8 on 2026-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_travelpackage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='travel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
