# Generated by Django 5.2.8 on 2025-12-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_travelpackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='image',
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.travelpackage')),
            ],
        ),
    ]
