# Generated by Django 5.2.8 on 2026-01-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_travelpackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='image',
        ),
    ]
