# Generated by Django 5.2.8 on 2026-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedayoption',
            name='action_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
