# Generated by Django 5.2.8 on 2025-12-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_travelpackage_image_packageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
