# Generated by Django 5.2.8 on 2025-12-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_travelpackage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('honeymoon', 'Honeymoon'), ('family', 'Family'), ('religious', 'Religious'), ('luxury', 'Luxury')], default='adventure', max_length=20),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='inclusions',
            field=models.JSONField(default=list, help_text="e.g. ['Breakfast', 'Wifi', 'Guide']"),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
