# Generated by Django 5.2.8 on 2026-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_is_verified_userprofile_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='travel_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
