# Generated by Django 5.2.8 on 2026-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_travelpackage_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='travel_type',
            field=models.CharField(max_length=255),
        ),
    ]
