# Generated by Django 5.2.8 on 2026-01-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_travelpackage_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='country',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='inclusions',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='slug',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='hotel_info',
            field=models.TextField(blank=True, help_text='Details about accommodation', null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='travel_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('relax', 'Relaxation'), ('cultural', 'Cultural'), ('city_break', 'City Break'), ('beach', 'Beach'), ('nature', 'Nature & Wildlife'), ('cruise', 'Cruise')], default='relax', help_text='Category of travel', max_length=50),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='location',
            field=models.CharField(help_text='e.g., Paris, France', max_length=255),
        ),
    ]
