# Generated by Django 5.2.8 on 2026-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_notification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="main_notifi_user_id_844422_idx",
            old_name="main_notifi_user_id_c24bc3_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="main_notifi_user_id_db2a78_idx",
            old_name="main_notifi_user_id_1c807b_idx",
        ),
    ]
