# Generated by Django 5.2.8 on 2026-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emailotp_emailverification'),
        ('main', '0010_rename_main_notifi_user_id_c24bc3_idx_main_notifi_user_id_844422_idx_and_more'),
    ]

    operations = [
    ]
