# Generated by Django 5.2.8 on 2026-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_travelpackage_sponsorship_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='id_document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('citizenship', 'Citizenship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pan_cards/'),
        ),
    ]
