# Generated by Django 5.2.8 on 2026-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_vendor_id_document_photo_vendor_id_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
