# Generated by Django 5.2.8 on 2026-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_vendor_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
