# Generated by Django 5.2.8 on 2026-03-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_travelpackage_moderated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_review', 'In Review'), ('cancellation_requested', 'Cancellation Requested'), ('cancellation_reviewed', 'Waiting Admin Decision'), ('partially_refunded', 'Partially Refunded'), ('refund_processed', 'Refund Processed'), ('trip_completed', 'Trip Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(blank=True, max_length=200)),
                ('guide_contact', models.CharField(blank=True, max_length=100)),
                ('jeep_driver_name', models.CharField(blank=True, max_length=200)),
                ('jeep_plate_number', models.CharField(blank=True, max_length=100)),
                ('hotel_name', models.CharField(blank=True, max_length=200)),
                ('hotel_confirmation_code', models.CharField(blank=True, max_length=100)),
                ('permit_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('applied', 'Applied'), ('approved', 'Approved')], default='not_required', max_length=20)),
                ('permit_reference', models.CharField(blank=True, max_length=120)),
                ('operation_notes', models.TextField(blank=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='booking_documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='main.booking')),
            ],
        ),
    ]
