# Generated by Django 5.2.8 on 2026-03-30 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userprofile_account_deletion_request_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='max_travelers',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='BookingCapacityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.PositiveIntegerField(default=1)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Vendor Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted To Booking')], default='pending', max_length=20)),
                ('vendor_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_payment_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_requests', to='main.travelpackage')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
